# Copyright 2023 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: slurmctld charm tests
on:
  workflow_call:
  pull_request:

jobs:
  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run tests
        run: tox -e unit

  type-check:
    name: Static type checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run tests
        run: tox -e type

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        bases:
          - ubuntu@22.04
        local: [true, false]
    name: Integration tests (LXD) ${{ matrix.local && '|' || '| Charmhub (edge) |'}} ${{ matrix.bases }}
    runs-on: ubuntu-latest
    # Testing against Charmhub will probably yield errors when doing breaking changes, so don't
    # block CI on that.
    continue-on-error: ${{ !matrix.local }}
    needs:
      - inclusive-naming-check
      - lint
      - unit-test
      - type-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Fetch slurmd
        uses: actions/checkout@v4
        if: ${{ matrix.local }}
        with:
          repository: charmed-hpc/slurmd-operator
          path: slurmd-operator
      - name: Fetch slurmdbd
        uses: actions/checkout@v4
        if: ${{ matrix.local }}
        with:
          repository: charmed-hpc/slurmdbd-operator
          path: slurmdbd-operator
      - name: Fetch slurmrestd
        uses: actions/checkout@v4
        if: ${{ matrix.local }}
        with:
          repository: charmed-hpc/slurmrestd-operator
          path: slurmrestd-operator
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 3.4/stable
      - name: Run tests
        run: |
          cd main && tox run -e integration -- \
             --charm-base=${{ matrix.bases }} \
             ${{ matrix.local && '--use-local' || '' }}
